#include <stdio.h>
void main()
{
    int decimal;
    int quotient;
    int remainder;
    int i;
    int j;
    char hexadecimal[100];

    printf("Enter a decimal number to be converted into hexadecimal number: ");
    scanf("%d", &decimal);

    quotient = decimal;
    while (quotient != 0)
    {
        remainder = quotient % 16;
        if (remainder < 10)
        {
            hexadecimal[j++] = remainder + 48;
        }
        else
        {
            hexadecimal[j++] = remainder + 55;
        }
        quotient = quotient / 16;
    }
    printf("\n------------------------------------------------\n");
    printf("The hexadecimal code generated by the code is: \n");
    for (i = j; i >= 0; i--)
    {
        printf("%c", hexadecimal[i]);
    }
}

/*
#include <stdio.h>
void main()
{
    int num;
    int a, b, c;
    a = 0;
    b = 1;
    int i;
    int missingno;
    printf("Enter the number of numbers do you want in a fibonacci series: ");
    scanf("%d", &num);
    printf("Enter the number of missing elements you want to display in the output: ");
    scanf("%d", &missingno);
    int arr[num];
    arr[0] = a;
    arr[1] = b;
    for(i = 0; i < num; i ++)
    {
        c = a + b;
        arr[i+2] = c;
        a = b;
        b = c;
    }
    int j = 0;
    int flag = 1;
    int k = 1;
    for(i = 0; i < arr[num-1]; i ++)
    {
        if(k == missingno+1)
        {
            break;
        }
        for(j = 0; j < num; j ++)
        {
            if(i == arr[j])
            {
                flag = 0;
                break;
            }
        }
        if(flag == 1)
        {
            printf("%d ", i);
            k++;
        }
        flag = 1;
    }
}
*/
